routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['web']], function(){
      Route::resource('item','ItemController');
});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table = 'item';

    protected $fillable = array(
      'name',
      'many',
      'brand',
      'condition',
      'detail'
    );
}

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    Protected $table = 'item';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ItemController.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use DB;
use App\Item as Model;
use Illuminate\Http\Request;
use App\Http\Requests\CreateItem;

class ItemController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $model = 'model';
        $items = Model::orderBy('id', 'asc')->paginate(5);
        return view('item.index', compact('model','items'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        return view('item/create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(CreateItem $request)
    {
        $model = new Model();
        $model->name      = $request->get('name');
        $model->many      = $request->get('many');
        $model->brand     = $request->get('brand');
        $model->condition = $request->get('condition');
        $model->detail    = $request->get('detail');
        $model->save();
        return redirect()->route('item.index')
        ->with('message', 'Data Berhasil Tersimpan');
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        $model = 'model';
        $items = Model::findOrFail($id);
        return view('item\show', compact('model','items'));
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $model = 'model';
        $item  = Model::findOrFail($id);
        return view('item\edit', compact('model','item'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(CreateItem $request, Model $item)
    {
        $item->name      = $request->get('name');
        $item->many      = $request->get('many');
        $item->brand     = $request->get('brand');
        $item->condition = $request->get('condition');
        $item->detail    = $request->get('detail');
        $item->save();
        return redirect()->route('item.index')
        ->with('message', 'Data Berhasil Tersimpan');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        $items = Model::findOrFail($id);
        $items->delete();
        return redirect()->route('item.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="columns">
  <div class="column is-1"></div>
  <div class="column is-auto">
    <div class="card">
      <header class="card-header">
        <h1 class="card-header-title"> Inventory </h1>
      </header>
      <div class="card-content">
        <table class="table">
        <tr>
          <th>No</th>
          <th>Nama Barang</th>
          <th>Banyaknya</th>
          <th colspan="3">Keterangan</th>
        </tr>
        <?php foreach ($items as $item): ?>
          <tr>
            <td>{{ $item->id }}</td>
            <td>{{ $item->name }}</td>
            <td>{{ $item->many }}</td>
            <td> <a href="#" type="button" class="button is-link">Edit</a> </td>
            <td> <a href="#" type="button" class="button is-danger">Delete</a> </td>
            <td> <a href="#" type="button" class="button is-info">Detail</a> </td>
          </tr>
        <?php endforeach; ?>
      </table>
      </div>
    </div>
  </div>
  <div class="column is-1"></div>
</div>
@endsection

resources/views/item/create.blade.php
@extends('layouts.app')

@section('content')
<div class="columns">
    <div class="column is-3"></div>
    <div class="column is-auto">
        <div class="card">
            <header class="card-header">
                <h1 class="card-header-title">
                    <a href="{{ URL::previous() }}" type="button" class="button is-info">
                        <span class="icon"><i class="fas fa-arrow-left"></i></span>
                    </a>
                    &nbsp;
                    Inventory
                </h1>

            </header>
            <div class="card-content">

                {!! Form::open(['url' => 'item']) !!}
                <div class="field">
                    {!! Form::label('name', 'Nama Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::text('name', '',['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('name')) ? $errors->first('name') : '' }}</p>
                </div>

                <div class="field">
                    {!! Form::label('brand', 'Merek Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::text('brand', '',['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('brand')) ? $errors->first('brand') : '' }}</p>
                </div>

                <div class="field">
                    {!! Form::label('many', 'jumlah Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::number('many', '',['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('many')) ? $errors->first('many') : '' }}</p>
                </div>

                <div class="field">
                    <div class="control">
                        {!! Form::select('condition', ['Bagus' => 'Bagus', 'Rusak' => 'Rusak'], null, ['placeholder' => 'Kondisi Barang', 'class' => 'select']); !!}
                    </div>
                </div>

                <div class="field">
                    {!! Form::label('detail', 'Detail Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::textarea('detail', '',['class' => 'textarea']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('detail')) ? $errors->first('detail') : '' }}</p>
                </div>

                <div class="field">
                    <div class="control">
                        {!! Form::submit('SUBMIT',['class'=>'button']); !!}
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <div class="column is-3"></div>
</div>
@endsection

resources/views/item/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="columns">
    <div class="column is-3"></div>
    <div class="column is-auto">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    <a href="{{ URL::previous() }}" type="button" class="button is-info">
                        <span class="icon"><i class="fas fa-arrow-left"></i></span>
                    </a>
                    &nbsp;
                    Edit Barang
                </p>

            </header>
            <div class="card-content">

                {!! Form::model('$item',['method' => 'PATCH', 'action' => ['ItemController@update',$item->id]]) !!}
                <div class="field">
                    {!! Form::label('name', 'Nama Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::text('name', $item->name,['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('name')) ? $errors->first('name') : '' }}</p>
                </div>

                <div class="field">
                    {!! Form::label('brand', 'Merek Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::text('brand', $item->brand,['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('brand')) ? $errors->first('brand') : '' }}</p>
                </div>

                <div class="field">
                    {!! Form::label('many', 'jumlah Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::number('many', $item->many,['class' => 'input']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('many')) ? $errors->first('many') : '' }}</p>
                </div>

                <div class="field">
                    <div class="control">
                        {!! Form::select('condition', ['Bagus' => 'Bagus', 'Rusak' => 'Rusak'],$item->condition, ['placeholder' => 'Kondisi Barang', 'class' => 'select']); !!}
                    </div>
                </div>

                <div class="field">
                    {!! Form::label('detail', 'Detail Barang',['class' => 'label']); !!}
                    <div class="control">
                        {!! Form::textarea('detail', $item->detail, ['class' => 'textarea']); !!}
                    </div>
                    <p class="help is-danger">{{ ($errors -> has('detail')) ? $errors->first('detail') : '' }}</p>
                </div>

                <div class="field">
                    <div class="control">
                        {!! Form::submit('SUBMIT',['class'=>'button']); !!}
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    <div class="column is-3"></div>
</div>
@endsection

@section('footer')
@include('layouts.footer')
@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('content')
<div class="columns">
    <div class="column is-1"></div>
    <div class="column is-auto">

        @if(Session::has('message'))
        <div class="notification is-primary">
            <button class="delete" aria-label="close"></button>
            {{ Session::get('message') }}
        </div>
        @endif

        <div class="card">
            <header class="card-header">
                <h1 class="card-header-title">
                    Inventory
                    &nbsp;
                    <a href="{{ route('item.create') }}" class="button is-primary is-pulled-right">
                        <span class="icon"><i class="fas fa-plus"></i></span>
                    </a>
                </h1>
            </header>
            <div class="card-content">
                <table class="table is-fullwidth">
                    <tr>
                        <th>No</th>
                        <th>Nama Barang</th>
                        <th>Merek</th>
                        <th>Banyak</th>
                        <th>Kondisi</th>
                        <th colspan="3">Keterangan</th>
                    </tr>
                    @foreach ($items as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->brand }}</td>
                            <td>{{ $item->many }}</td>
                            <td>{{ $item->condition }}</td>
                            <td> <a href="{{ route('item.edit',$item->id) }}" type="button" class="button is-warning">
                                    <span class="icon"><i class="fas fa-edit"></i></span>
                                </a>
                            </td>
                            <td> <a href="{{ route('item.show',$item->id) }}" type="button" class="button is-info">
                                    <span class="icon"><i class="fas fa-eye"></i></span>
                                </a>
                            </td>
                            <td>
                                <button   type="button" name="button" class="button is-danger deleteButton modal-button"  data-target="modal-confirm-delete-{{$item->id}}">
                                    <span class="icon"><i class="fas fa-trash-alt"></i></span>
                                </button>
                                <div class="modal" id="modal-confirm-delete-{{$item->id}}">
                                    <div class="modal-background"></div>
                                    <div class="modal-card is-radiusless">
                                        <header class="modal-card-head is-radiusless">
                                            <p class="modal-card-title">Konfirmasi Penghapusan Data Inventory</p>
                                            <button class="delete" aria-label="close"></button>
                                        </header>

                                        <section class="modal-card-body">
                                            <p class="has-text-center">Apakah Anda Yakin Ingin Menghapus Data Inventory ini ?</p>
                                        </section>

                                        <footer class="modal-card-foot is-flex" style="justify-content: flex-end;">

                                            <a class="button is-success is-radiusless button-close-modal">
                                                <span class="icon is-large">
                                                    <i class="fas fa-window-close" aria-hidden="true"></i>
                                                </span>
                                                &nbsp;
                                                Batal
                                            </a>

                                            <form action="{{ route('item.destroy',$item->id) }}" method="post">
                                                {{ method_field('DELETE') }}
                                                @csrf

                                                <button class="button is-danger" type="submit">
                                                    <span class="icon is-large">
                                                        <i class="fas fa-trash" aria-hidden="true"></i>
                                                    </span>
                                                    &nbsp;
                                                    Konfirmasi
                                                </button>
                                            </form>
                                        </footer>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <footer>
                {{ $items->links('vendor.pagination.bulma') }}
            </footer>
        </div>
    </div>
    <div class="column is-1"></div>
</div>
@endsection
@section('javascript')
<script>
document.addEventListener('DOMContentLoaded', function () {
    function getAll(selector) {
        return Array.prototype.slice.call(document.querySelectorAll(selector), 0);
    }
    var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {
        // Add a click event on each of them
        $navbarBurgers.forEach(function ($el) {
            $el.addEventListener('click', function () {
                // Get the target from the "data-target" attribute
                var target = $el.dataset.target;
                var $target = document.getElementById(target);
                // Toggle the class on both the "navbar-burger" and the "navbar-menu"
                $el.classList.toggle('is-active');
                $target.classList.toggle('is-active');
            });
        });
    }
    // modal handler
    // Modals
    var rootEl = document.documentElement;
    var $modals = getAll('.modal');
    var $modalButtons = getAll('.modal-button');
    var $modalCloses = getAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button-close-modal');
    if ($modalButtons.length > 0) {
        $modalButtons.forEach(function ($el) {
            $el.addEventListener('click', function () {
                var target = $el.dataset.target;
                var $target = document.getElementById(target);
                rootEl.classList.add('is-clipped');
                $target.classList.add('is-active');
            });
        });
    }

    if ($modalCloses.length > 0) {
        $modalCloses.forEach(function ($el) {
            $el.addEventListener('click', function () {
                closeModals();
            });
        });
    }

    document.addEventListener('keydown', function (event) {
        var e = event || window.event;
        if (e.keyCode === 27) {
            closeModals();
            closeDropdowns();
        }
    });

    function closeModals() {
        rootEl.classList.remove('is-clipped');
        $modals.forEach(function ($el) {
            $el.classList.remove('is-active');
        });
    }
    // Dropdowns
    var $dropdowns = getAll('.dropdown:not(.is-hoverable)');
    if ($dropdowns.length > 0) {
        $dropdowns.forEach(function ($el) {
            $el.addEventListener('click', function (event) {
                event.stopPropagation();
                $el.classList.toggle('is-active');
            });
        });
        document.addEventListener('click', function (event) {
            closeDropdowns();
        });
    }
    function closeDropdowns() {
        $dropdowns.forEach(function ($el) {
            $el.classList.remove('is-active');
        });
    }
});

$(document).on('click', '.notification > button.delete', function() {
    $(this).parent().addClass('is-hidden');
    return false;
});
</script>
@endsection

resources/views/item/show.blade.php
@extends('layouts.app')

@section('content')

<div class="columns">
    <div class="column is-1"></div>
    <div class="column is-auto">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    <a href="{{ URL::previous() }}" type="button" class="button is-info">
                        <span class="icon"><i class="fas fa-arrow-left"></i></span>
                    </a>
                    &nbsp;
                    Data Barang
                </p>
            </header>
            <div class="card-content">
                <div class="content">
                    <table class="table is-fullwidth">
                        <tr>
                            <th>Nama Barang</th>
                            <td>: {{ $items->name }}</td>
                        </tr>
                        <tr>
                            <th>Merek Barang</th>
                            <td>: {{ $items->brand }}</td>
                        </tr>
                        <tr>
                            <th>Jumlah Barang</th>
                            <td>: {{ $items->many }}</td>
                        </tr>
                        <tr>
                            <th>Kondisi Barang</th>
                            <td>: {{ $items->condition }}</td>
                        </tr>
                        <tr>
                            <th>Detail</th>
                            <td>: {{ $items->detail }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="column is-1"></div>
</div>



@endsection

@section('footer')
@include('layouts.footer')
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/bulma.css') }}" rel="stylesheet">

    <!-- Styles -->


</head>
<body>
    <nav class="navbar is-dark" data-bulma="navbar">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url('/') }}">
                <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navMenuExample" data-trigger>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navMenuExample" class="navbar-menu">
            @guest
            <div class="navbar-start is-pulled-right">

            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a class="navbar-item has-text-white" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </p >
                        <p class="control">
                            <a class="navbar-item has-text-white" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </p>
                    </div>
                </div>
            </div>
            @else
            <div class="navbar-start">
                <a class="navbar-item has-text-white" href="{{ route('item.index') }}">
                    Home
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link has-text-white" href="/documentation/overview/start/">
                        Docs
                    </a>
                    <div class="navbar-dropdown is-boxed">

                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <li class="navbar-item has-dropdown is-hoverable">
                                <a id="navbarDropdown" class="navbar-link" href="#"  v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="navbar-dropdown is-boxed" aria-labelledby="navbarDropdown">
                                    <a class="navbar-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </p >
                </div>
            </div>
        </div>
    </div>
</nav>
<br>
<main>

    @yield('content')
</main>
<br>
<footer>
    @include('layouts.footer')
</footer>
<script src="{{ asset('js/bulma.js') }}"></script>
<script src="{{ asset('js/modal.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script defer src="{{ asset('js/fontawesome-all.js') }}"></script>
@section('javascript')
@show
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer" id="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </div>
</footer>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ asset('favicon.ico') }}">
    <title>www.testblog.blogspot.co.id</title>
    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ asset('assets/css/ie10-viewport-bug-workaround.css') }}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/css/jumbotron-narrow.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="carousel.css">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{ asset('assets/js/ie-emulation-modes-warning.js') }}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <div class="header clearfix">
          @yield('header')
      </div>
      <div class="row">
          @yield('slide')
      </div>

      <div class="jumbotron">
        @yield('sidebar-up')
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          @yield('sidebar-left')
        </div>

        <div class="col-lg-6">
          @yield('sidebar-right')
        </div>
      </div>

      <footer class="footer">
        @yield('footer')
      </footer>

    </div> <!-- /container -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ asset('assets/js/ie10-viewport-bug-workaround.js') }}"></script>
  </body>
</html>